'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {siteConfig} from '@/lib/site-config';

function calendarHref(ev:(typeof siteConfig.events)[number]){
  const dt=ev.date.replaceAll('-','');
  const body=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Beek and The Cat//EN','BEGIN:VEVENT','UID:'+ev.id+'@beek-and-the-cat','DTSTART;VALUE=DATE:'+dt,'SUMMARY:'+ev.title,'LOCATION:'+ev.location.replace('SAMPLE — ',''),'DESCRIPTION:'+ev.description,'END:VEVENT','END:VCALENDAR'].join('\r\n');
  return 'data:text/calendar;charset=utf-8,'+encodeURIComponent(body);
}
function Countdown(){
  const next=useMemo(()=>siteConfig.events.map(e=>({...e,ts:new Date(e.date+'T12:00:00-04:00').getTime()})).find(e=>e.ts>Date.now()),[]);
  const [left,setLeft]=useState(next?Math.max(0,next.ts-Date.now()):0);
  useEffect(()=>{if(!next)return;const id=setInterval(()=>setLeft(Math.max(0,next.ts-Date.now())),1000);return()=>clearInterval(id)},[next]);
  if(!next)return <div className="card p-6 text-center font-bold">All listed events have passed. Time to blame the cat.</div>;
  const d=Math.floor(left/86400000),h=Math.floor((left%86400000)/3600000),m=Math.floor((left%3600000)/60000),s=Math.floor((left%60000)/1000);
  return <div className="card p-6 md:p-8"><p className="text-center font-bold mb-5">Counting down to {next.title} · {siteConfig.timezone}</p><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['days',d],['hours',h],['minutes',m],['seconds',s]].map(([l,v])=><div key={l} className="rounded-2xl border-[3px] border-[var(--plum)] bg-white p-4 text-center"><div className="display text-4xl">{v}</div><div className="text-sm font-bold uppercase">{l}</div></div>)}</div></div>
}
function RSVP(){
  const [state,setState]=useState<{kind:'idle'|'loading'|'success'|'error';message?:string}>({kind:'idle'});
  const [confetti,setConfetti]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){
    e.preventDefault();setState({kind:'loading'});setConfetti(false);const form=e.currentTarget;const fd=new FormData(form);
    const attendance=Object.fromEntries(siteConfig.events.map(ev=>[ev.id,fd.get(ev.id)]));
    const payload={name:fd.get('name'),email:fd.get('email'),guestCount:Number(fd.get('guestCount')),dietary:fd.get('dietary'),note:fd.get('note'),website:fd.get('website'),attendance};
    try{const res=await fetch('/api/rsvp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Unable to submit RSVP.');setState({kind:'success',message:'RSVP saved. We are officially excited.'});setConfetti(true);form.reset();setTimeout(()=>setConfetti(false),2500)}catch(err){setState({kind:'error',message:err instanceof Error?err.message:'Unable to submit RSVP.'})}
  }
  return <div className="relative"><form onSubmit={submit} className="card p-6 md:p-8 space-y-5"><div className="grid md:grid-cols-2 gap-5"><label className="font-bold">Name<input name="name" required maxLength={80} className="mt-2 w-full rounded-xl border-[3px] border-[var(--plum)] bg-white p-3 font-normal"/></label><label className="font-bold">Email<input name="email" type="email" required maxLength={160} className="mt-2 w-full rounded-xl border-[3px] border-[var(--plum)] bg-white p-3 font-normal"/></label></div><div className="hidden" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><fieldset><legend className="display text-2xl mb-3">Which chaos are you attending?</legend><div className="space-y-4">{siteConfig.events.map(ev=><div key={ev.id} className="rounded-2xl border-[3px] border-[var(--plum)] p-4 bg-white"><div className="font-black mb-2">{ev.title}</div><div className="flex flex-wrap gap-4">{['yes','no','maybe'].map(v=><label key={v}><input required type="radio" name={ev.id} value={v}/> {v[0].toUpperCase()+v.slice(1)}</label>)}</div></div>)}</div></fieldset><label className="font-bold block">Guest count<select name="guestCount" defaultValue="1" className="mt-2 w-full rounded-xl border-[3px] border-[var(--plum)] bg-white p-3 font-normal">{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label><label className="font-bold block">Dietary restrictions / allergies<textarea name="dietary" maxLength={500} rows={3} className="mt-2 w-full rounded-xl border-[3px] border-[var(--plum)] bg-white p-3 font-normal"/></label><label className="font-bold block">Optional note<textarea name="note" maxLength={1000} rows={4} className="mt-2 w-full rounded-xl border-[3px] border-[var(--plum)] bg-white p-3 font-normal"/></label><button className="btn pink" disabled={state.kind==='loading'}>{state.kind==='loading'?'Submitting…':'Send RSVP'}</button>{state.message&&<p role="status" className={state.kind==='error'?'font-bold text-red-700':'font-bold text-green-800'}>{state.message}</p>}</form>{confetti&&<div aria-hidden="true" className="pointer-events-none absolute inset-0 overflow-hidden">{Array.from({length:18}).map((_,i)=><span key={i} className="absolute text-2xl animate-bounce" style={{left:((i*37)%100)+'%',top:((i*23)%80)+'%'}}>🎉</span>)}</div>}</div>
}
export default function Home(){
 const [active,setActive]=useState<number|null>(null);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')setActive(null)};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[]);
 return <main>
 <header className="sticky top-0 z-50 border-b-[3px] border-[var(--plum)] bg-[rgba(255,244,227,.96)] backdrop-blur"><div className="wrap px-5 h-[76px] flex items-center justify-between gap-4"><a href="#top" className="display text-xl no-underline">🐾 {siteConfig.brand}</a><nav aria-label="Main navigation" className="flex flex-wrap justify-end gap-3 text-sm font-black"><a href="#events">Events</a><a href="#photos">Photos</a><a href="#faq">FAQ</a><a href="#rsvp">RSVP</a></nav></div></header>
 <section id="top" className="section pt-12 md:pt-20"><div className="wrap grid lg:grid-cols-[1.1fr_.9fr] gap-10 items-center"><div><div className="inline-block rotate-[-2deg] rounded-full border-[3px] border-[var(--plum)] bg-[var(--yellow)] px-4 py-2 font-black mb-5">ONE WEEKEND · THREE EVENTS · ZERO RESTRAINT</div><h1 className="display text-6xl md:text-8xl leading-[.9] mb-6">Beek <span className="text-[var(--pink)]">&</span><br/>The Cat</h1><p className="text-xl md:text-2xl max-w-2xl mb-7">{siteConfig.coupleLine}</p><div className="flex flex-wrap gap-4"><a className="btn pink" href="#rsvp">RSVP</a><a className="btn yellow" href="#events">See the events</a></div><p className="mt-6 font-bold">🐾 paw-approved-ish · ✨ scrapbook energy · 🐈 cat veto pending</p></div><div className="card p-6 rotate-2 min-h-[420px] flex items-center justify-center bg-[var(--yellow)]"><div className="text-center"><div className="text-7xl">📸</div><div className="display text-4xl mt-4">HERO PHOTO</div><p className="font-bold mt-2">Replace this placeholder in the config/layout later.</p></div></div></div></section>
 <section className="section pt-0"><div className="wrap"><Countdown/></div></section>
 <section id="events" className="section"><div className="wrap"><h2 className="display text-5xl md:text-6xl mb-3">The events</h2><p className="text-lg mb-8 max-w-2xl">Useful details first. Jokes second. All dates and locations below are <strong>sample placeholders</strong> until configured.</p><div className="grid-auto">{siteConfig.events.map((ev,i)=><article key={ev.id} className="card p-6"><div className="font-black text-sm uppercase text-[var(--purple)]">Sample event {i+1}</div><h3 className="display text-3xl mt-2 mb-4">{ev.title}</h3><p><strong>Date:</strong> {ev.date}</p><p><strong>Time:</strong> {ev.time}</p><p><strong>Location:</strong> {ev.location}</p><p><strong>Dress code:</strong> {ev.dressCode}</p><p className="mt-4">{ev.description}</p><a download={ev.id+'.ics'} href={calendarHref(ev)} className="btn yellow mt-5">Add to calendar</a></article>)}</div></div></section>
 <section id="photos" className="section"><div className="wrap"><h2 className="display text-5xl md:text-6xl mb-3">Photo scrapbook</h2><p className="mb-8 text-lg">Labeled placeholders are intentionally used instead of copying personal photos from the reference.</p><div className="grid md:grid-cols-2 gap-7">{siteConfig.photos.map((p,i)=><button key={p.label} onClick={()=>setActive(i)} className={'card min-h-[320px] p-6 text-left '+(i%2?'md:rotate-2':'md:-rotate-2')}><div className="h-[220px] rounded-2xl border-[3px] border-[var(--plum)] bg-[var(--yellow)] flex items-center justify-center display text-4xl">{p.label}</div><span className="block pt-4 font-bold">{p.caption}</span></button>)}</div></div></section>
 {active!==null&&<div role="dialog" aria-modal="true" aria-label="Photo viewer" className="fixed inset-0 z-[100] bg-[rgba(36,19,41,.86)] p-5 flex items-center justify-center" onClick={()=>setActive(null)}><div className="card max-w-2xl w-full p-6 bg-white" onClick={e=>e.stopPropagation()}><button className="btn yellow mb-5" onClick={()=>setActive(null)}>Close</button><div className="h-[360px] rounded-2xl border-[3px] border-[var(--plum)] bg-[var(--yellow)] flex items-center justify-center display text-5xl">{siteConfig.photos[active].label}</div><p className="pt-4 font-bold">{siteConfig.photos[active].caption}</p></div></div>}
 <section className="section"><div className="wrap"><h2 className="display text-5xl md:text-6xl mb-8">Gift ideas</h2><div className="grid-auto">{siteConfig.gifts.map(g=><article key={g.title} className="card p-6"><h3 className="display text-3xl mb-3">{g.title}</h3><p>{g.description}</p>{g.url?<a className="btn pink mt-5" href={g.url} target="_blank" rel="noreferrer">Open registry</a>:<p className="mt-5 font-bold text-sm">Registry link not configured yet.</p>}</article>)}</div></div></section>
 <section id="faq" className="section"><div className="wrap max-w-4xl"><h2 className="display text-5xl md:text-6xl mb-8">FAQ</h2><div className="space-y-4">{siteConfig.faq.map(item=><details key={item.q} className="card p-5"><summary className="cursor-pointer font-black text-xl">{item.q}</summary><p className="pt-4">{item.a}</p></details>)}</div></div></section>
 <section id="rsvp" className="section"><div className="wrap max-w-4xl"><h2 className="display text-5xl md:text-6xl mb-3">RSVP</h2><p className="text-lg mb-8">The form only confirms success after the server saves your response.</p><RSVP/></div></section>
 <footer className="border-t-[3px] border-[var(--plum)] py-10 px-5"><div className="wrap flex flex-col md:flex-row gap-4 justify-between"><p className="font-black">Made with love, questionable judgment, and cat supervision.</p><nav className="flex gap-4 font-bold"><a href="#events">Events</a><a href="#photos">Photos</a><a href="#faq">FAQ</a><a href="#top">Top ↑</a></nav></div></footer>
 </main>
}